//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleDBConnection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlQuery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlQuery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleDBConnection.Properties.SqlQuery", typeof(SqlQuery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  p.name, count(distinct t.name) AS val FROM test t
        ///left join project p on p.id = t.project_id
        ///group by p.name
        ///order by  p.name;.
        /// </summary>
        internal static string CountUniqueTests {
            get {
                return ResourceManager.GetString("CountUniqueTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  p.name, t.name, Min(t.end_time-t.start_time) AS val FROM test t
        ///                         right join project p on p.id = t.project_id 
        ///                         group by t.name 
        ///                         order by p.name, t.name;.
        /// </summary>
        internal static string MinTimeTestWorkQuery {
            get {
                return ResourceManager.GetString("MinTimeTestWorkQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  p.name,  t.name, t.start_time FROM test t
        ///left join project p on p.id = t.project_id
        ///where t.start_time&gt;=&apos;2015-11-7 00:00:00&apos;
        ///order by  p.name, t.name;.
        /// </summary>
        internal static string TestsAfterDate {
            get {
                return ResourceManager.GetString("TestsAfterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT browser, count(*) as browser FROM test
        ///where browser = &apos;firefox&apos;
        ///group by browser
        ///union
        ///SELECT browser, count(*) as browser FROM test
        ///where browser = &apos;chrome&apos;
        ///group by browser;.
        /// </summary>
        internal static string TestsRunningOnBrowser {
            get {
                return ResourceManager.GetString("TestsRunningOnBrowser", resourceCulture);
            }
        }
    }
}
